# Generated by Django 4.1.4 on 2022-12-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='MP', max_length=3),
        ),
    ]
